[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

; This line tells the S3 to use the fast External RAM (PSRAM)
board_build.arduino.memory_type = qio_opi 
monitor_speed = 115200